schema/load_test.go, schema/scenario.go, schema/testdata/valid-anchor.yaml
=> add(schema): add anchors field

context/extract_test.go, context/plugins.go, testdata/plugins/simple/main.go
Return the value that the pointer points to.
=> change(context): return the actual value

assert/equal.go, assert/equal_test.go, testdata/proto/test/test.proto, testdata/scenarios/grpc.yaml
Add support for checking null value.
=> fix: enable to expect null

go.mod, go.sum, runner_test.go, schema/retry.go, schema/retry_test.go, schema/scenario.go, step.go, testdata/scenarios/complex.yaml
```yaml
steps:
- title: POST /get
protocol: http
request:
method: POST
url: "{{env.TEST_ADDR}}/count"
expect:
body: "2"
retry:
constant:
interval: 1s
maxRetries: 1
```
```yaml
steps:
- title: POST /get
protocol: http
request:
method: POST
url: "{{env.TEST_ADDR}}/count"
expect:
body: "2"
retry:
exponential:
initialInterval: 1s
factor: 2
jitterFactor: 0.2
maxInterval: 5s
maxElapsedTime: 30s
maxRetries: 10
```
=> Implement retry config

runner_test.go, step.go, testdata/base.yaml, testdata/base_error.yaml, testdata/use_include.yaml, testdata/use_include_error.yaml
Related feature is #33 
Supports `include` 🎉
=> Support to output error with YAML in 'include' feature

errors/error.go, errors/error_test.go, go.mod, go.sum
FYI https://github.com/goccy/go-yaml/pull/131
=> Fix incorrect line number in YAML source

go.mod, go.sum
FYI: https://github.com/goccy/go-yaml/pull/132
=> Update YAML library ( v1.7.8 => v1.7.9 )

go.mod, go.sum, test/e2e/testdata/scenarios/http.yaml
FYI: https://github.com/goccy/go-yaml/pull/133
=> Update YAML library ( v1.7.9 => v1.7.10 )

go.mod, go.sum
FYI: https://github.com/goccy/go-yaml/pull/134
=> Update YAML library ( v1.7.10 => v1.7.11 )

go.mod, go.sum, test/e2e/testdata/scenarios/http.yaml
FYI: https://github.com/goccy/go-yaml/pull/135
=> Update YAML library ( v1.7.11 => v1.7.12 )

template/template.go, template/template_test.go
=> Add validation for argument of function

go.mod, go.sum
FYI:
- https://github.com/goccy/go-yaml/pull/136
- https://github.com/goccy/go-yaml/pull/137
- https://github.com/goccy/go-yaml/pull/138
=> Update YAML library ( v1.7.12 => v1.7.15 )

step.go
=> Measure and Report elapsed time about invoking request and plugin

template/template.go, template/template_test.go
Left arrow function unmarshals the YAML string into the Go value and will be executed with it, so the argument must be a YAML string.
Therefore, Scenarigo replaces functions into a string temporary when executing template parameters in arguments of left arrow function.
https://github.com/zoncoen/scenarigo/blob/d64ae8e7f733d02a1c56b45a14ae7642e9faa273/template/template.go#L108-L118
Scenarigo must restore the replaced functions before executing the left arrow functions to pass the argument correctly.
=> fix(template): enable to use function variables in arguments of left arrow function

assert/operator.go, assert/operator_test.go, context/assert.go, test/e2e/testdata/scenarios/assert.yaml
Add the "and" operator for assertions.
=> feat(assert): add "and" function

assert/regexp.go, assert/regexp_test.go, context/assert.go, test/e2e/testdata/scenarios/assert.yaml
Add "regexp" assertion to check whether a value matches the regular expression pattern or not.
This PR resolves https://github.com/zoncoen/scenarigo/issues/68.
=> feat(assert): add regexp function

runner.go, runner_test.go, schema/load.go, schema/load_test.go
Add `WithScenariosFromReader` option to read the scenario directly without file I/O .
=> Add WithScenariosFromReader option

assert/assertion.go, assert/assertion_test.go, assert/compare.go, assert/equal.go, assert/equal_test.go, assert/greater.go, assert/greater_test.go, assert/less.go, assert/less_test.go, assert/regexp.go, context/assert.go, test/e2e/testdata/scenarios/assert.yaml
add `greaterThan` , `greaterThanOrEqual` , `lessThan` , `lessThanOrEqual` as the function of assertion for comparing two values.
=> Add Greater/GreaterOrEqual/Less/LessOrEqual as assertion API

assert/assertion.go, assert/contains.go, assert/contains_test.go, assert/equal.go, assert/equal_test.go, assert/length.go, assert/length_test.go, assert/not_zero.go, assert/not_zero_test.go, assert/operator.go, assert/operator_test.go, assert/regexp.go, assert/regexp_test.go, context/assert.go, errors/error.go, errors/error_test.go, protocol/http/unmarshaler/json_test.go, test/e2e/testdata/scenarios/assert.yaml
Add "length" assertion to check whether a value has the expected length or not.
=> feat(assert): add length assertion

.github/workflows/generate-credits.yml, .github/workflows/test.yml
Generate `CREDITS` file and push it on dependabot PRs.
=> Re-generate CREDITS for dependabot

.github/workflows/generate-credits.yml
ref. https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks
=> chore: use pull_request_target to pass secrets

go.mod, go.sum, protocol/grpc/request_test.go, query/extractor/key.go, query/extractor/key_test.go
Accessing an unexported field causes panic.
=> Don't access unexported fields

runner.go, runner_test.go, setup.go, setup_test.go
Don't open plugins as of the time loading configuration file.
=> defer opening plugins

cmd/scenarigo/cmd/plugin/build.go, cmd/scenarigo/cmd/plugin/build_test.go
Don't print the warning log like `WARN: /path/to/go.mod replace google.golang.org/grpc v1.46.0 => v1.40.0` if the module has been replaced already.
=> fix(plugin): suppress unnecessary plugin build logs

.github/workflows/generate-credits.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/reviewdog.yml, .github/workflows/test.yml
=> chore: use go1.19 for CI

go.mod, go.sum, internal/reflectutil/set_test.go, internal/testutil/pointer.go, internal/testutil/pointer_test.go, template/template.go, template/template_test.go
Enable to call methods in template strings.
```
{{plugins.plugin.Struct.Echo("aaa")}}
```
```golang
type Struct struct{}
func (s Struct) Echo(str string) string {
return str
}
```
=> feat(template): enable to call methods

README.md, cmd/scenarigo/cmd/config/load.go, cmd/scenarigo/cmd/config/load_test.go, cmd/scenarigo/cmd/config/validate.go, cmd/scenarigo/cmd/list.go, cmd/scenarigo/cmd/plugin/build.go, cmd/scenarigo/cmd/plugin/list.go, cmd/scenarigo/cmd/root.go, cmd/scenarigo/cmd/run.go, schema/config.go, schema/config_test.go, schema/testdata/config/valid.yaml
Enable passing configuration via stdin instead of specifying a file path.
=> feat: enable to read config from stdin

CREDITS, go.mod, go.sum, protocol/http/request.go, protocol/http/request_test.go, protocol/http/unmarshaler/html.go, protocol/http/unmarshaler/html_test.go
- feat(http): add text/html unmarshaler
- feat(http): enable decoding of response bodies with character encodings other than utf-8
=> Print text/html response body as string

.github/workflows/release.yml, plugin/testing.go, plugin/testing_test.go, scripts/cross-build/cross-build/main.go
Enable to write tests for plugins.
=> fix(plugin): make RegisterSetup() not cause an error if called in tests

go.mod, protocol/grpc/expect.go, protocol/grpc/expect_test.go, protocol/grpc/request.go, protocol/grpc/request_test.go, protocol/grpc/type.go
`github.com/golang/protobuf` is deprecated.
ref. https://github.com/golang/protobuf/pull/1306
=> chore: use google.golang.org/protobuf only

.github/workflows/cross-build.yml, .github/workflows/generate-credits.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/reviewdog.yml, .github/workflows/run-examples.yml, .github/workflows/test.yml, CREDITS, README.md, cmd/scenarigo/cmd/plugin/build_test.go, cmd/scenarigo/cmd/plugin/testdata/git/dependent-gomodule/go.mod, cmd/scenarigo/cmd/plugin/testdata/git/dependent-gomodule/v2/go.mod, cmd/scenarigo/cmd/plugin/testdata/git/gomodule/go.mod, cmd/scenarigo/cmd/plugin/testdata/git/gomodule/v2/go.mod, cmd/scenarigo/cmd/plugin/testdata/git/plugin/go.mod, cmd/scenarigo/cmd/plugin/testdata/git/sub/go.mod, examples/ytt/plugin/src/go.mod, go.mod, go.sum, scripts/bump-go-version.sh, scripts/cross-build/build-matrix/main.go, scripts/cross-build/cross-build/main.go, scripts/cross-build/go.mod
=> chore: bump Go versions

runner_test.go, schema/load.go
`go-yaml` v1.11.1 fixes [the issue](https://github.com/zoncoen/scenarigo/issues/304). 🎉
=> refactor: remove workaround

scripts/cross-build/cross-build/main.go, scripts/cross-build/go.mod, scripts/cross-build/go.sum
=> chore(release): fix cross build script

schema/load_test.go, schema/scenario.go, schema/testdata/invalid-no-protocol.yaml, schema/testdata/invalid-unknown-protocol.yaml
=> fix: don't panic if the protocol is empty

assert/assertion_test.go, internal/reflectutil/set.go, internal/reflectutil/set_test.go, scenario_test.go, test/e2e/testdata/scenarios/assert.yaml
=> fix(template): don't convert int to string

CREDITS, Makefile, examples/assert/plugin/src/go.mod, examples/assert/plugin/src/go.sum, examples/step-if/plugin/src/go.mod, examples/step-if/plugin/src/go.sum, examples/ytt/plugin/src/go.mod, examples/ytt/plugin/src/go.sum, go.mod, go.sum, schema/load.go
=> chore(deps): bump carvel.dev/ytt from 0.45.4 to 0.48.0

.github/workflows/test.yml
=> chore(deps): bump codecov/codecov-action v3 to v4

go.mod, go.sum
=> chore(deps): bump golang.ort/x/* to the latest

.github/workflows/tagpr.yml
=> chore: introduce tagpr

cmd/scenarigo/cmd/plugin/build.go
I confirmed that the issue is not caused by homebrew.
=> chore: fix comment

cmd/scenarigo/cmd/plugin/build.go
fix flaky tests on macOS https://github.com/zoncoen/scenarigo/actions/runs/13023054217/job/36327383890?pr=439
=> retry flaky test

reporter/duration_unit_darwin_test.go
=> fix(test): change truncate unit to fix flaky tests on macOS

.github/workflows/bump-indirect-modules.yml
=> chore(ci): fix cron schedule

.github/dependabot.yml
To fix test's failure for dependabot
=> Add plugin/testdata/wasm/src directory to target for dependabot
