scenarigo/scenarigo

template/parser/parser.go
template/template_test.go

`template.Parser` could not handle a empty string.

fix: Parse returns nil node if empty string reader

---

context/extract_test.go
context/plugins.go
context/plugins_test.go
testdata/plugins/simple/main.go

`reflect.ValueOf(sym).Elem()` panics if `sym` is a function.

fix(context): fix a bug

---

protocol/http/request.go
protocol/http/request_test.go
runner_test.go
testdata/scenarios/http.yaml

Add query field to http request.
The query field is evaluated and will be merged with url field.
```yaml
protocol: http
request:
method: GET
url: "http://example.com/hello"
query:
id: 123
message: hey
```
will be equivalent to
```yaml
protocol: http
request:
method: GET
url: "http://example.com/hello?id=123&message=hey"
```
Basically, HTTP's GET method is not supposed to have a request body. Therefore some http servers deny GET requests that have a request body. In this case, sending GET requests with senarigo is a little bother. Adding query field makes yaml simpler and more readable.

add(http): add query field to http request

---

reporter/reporter.go
reporter/reporter_test.go

The tests are unstable on CI ubuntu-latest. (e.g. https://github.com/zoncoen/scenarigo/pull/26/checks?check_run_id=666266821

test: don't add duration to fix unstable tests

---

assert/equal.go
assert/equal_test.go
assert/not_zero.go
assert/not_zero_test.go
protocol/http/unmarshaler/json.go
protocol/http/unmarshaler/json_test.go

Use `json.Decoder` with `UseNumber` option to decode JSON response.
`json.Unmarshal` unmarshals all JSON numbers into an `interface{}` as a `float64` by default.
It may cause a rounding error when the number is the greater than 2^53 (9007199254740992).

fix: use json.Number to avoid rounding error

---

go.mod
go.sum
protocol/grpc/request.go
protocol/grpc/request_test.go
query/extractor/key.go
query/extractor/key_test.go
test/e2e/testdata/scenarios/grpc.yaml
test/e2e/testdata/scenarios/http.yaml

- Fix `ctx.Response()` for http protocol
- Support `anchor` / `alias` in `request` and `expect`
- Fix key extractor ( forgot processing of `yaml.MapSlice` or `yaml.MapItem` )

Fix ctx.Response() for http protocol

---

assert/assertion.go
assert/equal.go

Currently, output error without YAML in case of `assert.Contains` or `assert.NotContains` or `assert.NotZero` .
This PR fix the above problem .

Enable to output error with YAML even when using assert.Contains etc.

---

template/template.go
template/template_test.go

See https://golang.org/pkg/reflect/#Type
```
// IsVariadic reports whether a function type's final input parameter
// is a "..." parameter. If so, t.In(t.NumIn() - 1) returns the parameter's
// implicit actual type []T.
//
// For concreteness, if t represents func(x int, y ... float64), then
//
//	t.NumIn() == 2
//	t.In(0) is the reflect.Type for "int"
//	t.In(1) is the reflect.Type for "[]float64"
//	t.IsVariadic() == true
//
// IsVariadic panics if the type's Kind is not Func.
IsVariadic() bool
```

Fix processing for variadic arguments of function

---

cmd/scenarigo/cmd/list.go
cmd/scenarigo/cmd/list_test.go
runner.go
runner_test.go

```
$ scenarigo list --help
```
```
lists the test scenarios ( or steps of scenario )
Usage:
scenarigo list [flags]
Flags:
-f, --file      show file names only
-h, --help      help for list
-v, --verbose   show steps of scenario
```
The following are working under the `scenarigo` directory .
```
$ scenarigo list ./testdata
```
```
testdata/base.yaml//echo
testdata/base_error.yaml//echo
testdata/use_include.yaml//echo
testdata/use_include_error.yaml//echo
```
```
$ scenarigo list -v ./testdata
```
```
testdata/base.yaml//echo
testdata/base.yaml//echo/POST_/echo
testdata/base_error.yaml//echo
testdata/base_error.yaml//echo/POST_/echo
testdata/use_include.yaml//echo
testdata/use_include.yaml//echo/POST_/echo_by_include
testdata/use_include_error.yaml//echo …
```

Add list as sub command

---

protocol/grpc/request.go
protocol/grpc/request_test.go
protocol/http/request.go
protocol/http/request_test.go
reporter/reporter.go
reporter/reporter_test.go
reporter/testing.go
reporter/testing_test.go

- Need to indent for first line of log ( https://github.com/zoncoen/scenarigo/compare/master...goccy:feature/fix-log-format?expand=1#diff-366f112cf4c3ced1e7a80a3a4fdd325fR364 )
- FYI: https://github.com/golang/go/blob/master/src/testing/testing.go#L520-L557 
In order to solve the problem that unnecessary file name and number of lines were displayed when using testing.T,
write log directly to the buffer held by `testing.T` .
If this process failed, it falls back to the regular API.
FYI: https://github.com/golang/go/blob/master/src/testing/testing.go#L388

Improve log format

---

protocol/grpc/expect_test.go
protocol/grpc/grpc.go
protocol/grpc/grpc_test.go
protocol/http/http.go
protocol/http/http_test.go
schema/load_test.go
schema/scenario.go
schema/testdata/valid-without-expect.yaml
schema/testdata/valid-without-protocol.yaml

This PR modifies the unmarshaling process to set the default `AssertionBuilder` of a protocol to `Step` in case `expect` is empty, instead of skipping assertion. `UnmarshalExpect` of `http` and `grpc` is modified to return a default `AssertionBuilder` if the given bytes is nil. 
The default `AssertionBuilder`s i.e. `Expect`s of them are left as is, and only a few test cases to check its default behavior are added.
`http` and `grpc` checks the status code of the response is `OK` if the `expect.code` is empty but `expect.body` is not. However, if `expect` is empty, the assertion does not run at all because scenarigo sets nil to the `Expect.AssertionBuilder` of the step. It makes more sense to allow protocols to decide what to test by default in such case.

Use the default AssertionBuilder of a protocol if expect is empty

---

protocol/grpc/expect.go

Import `errdetails` package to register the proto messages (e.g.: `BadReqest`, `PreconditionFailure`, etc.). If they're not registered, it fails to decode `Any` message into a concrete type struct.

fix: register errdetails proto messages to unmarshal Any

---

protocol/http/unmarshaler/binary.go
protocol/http/unmarshaler/binary_test.go
protocol/http/unmarshaler/unmarshaler.go
protocol/http/unmarshaler/unmarshaler_test.go
test/e2e/testdata/scenarios/assert.yaml
testdata/base.yaml
testdata/use_include.yaml
testdata/use_include_error.yaml

Add binaryUnmarshaler that unmarshals response data as just a sequence of bytes, and use it as the default HTTP response unmarshaler.
This PR changes the default behavior but it makes more sense not to expect a certain data format when you don't know how to handle the given media type. You can also add a custom unmarshaler if necessary.

Add binaryUnmarshaler and use it as the default http response unmarshaler

---

protocol/grpc/grpc.go
protocol/grpc/grpc_test.go
protocol/http/http.go
protocol/http/http_test.go

Enable strict option when decoding yaml for expect to prevent tests falsely pass when fields are misplaced.
This patch prevents expect fields like the following: 
```
protocol: grpc
...
expect:
details:
- google.rpc.LocalizedMessage:
locale: ja-JP
message: message
```
This test passes regardless of `response.status.details` because `details` is placed directly under `expect`, not under `expect.status`. With this PR, the test fails when decoding the above yaml, preventing the test from falsely passing.

Enable strict option when decoding yaml for expect to prevent field misplacement

---

go.mod
go.sum
template/execute.go
template/execute_test.go
template/template.go

Get the pointer to a value when set to pointer value.
It fails to set a pointer value because `execute()` dereferences pointer values.

fix(template): enable to set to pointer values

---

template/execute.go
template/execute_test.go

`convert()` panics if the value is invalid.

fix(template): don't convert invalid values to avoid panic

---

reporter/duration_test.go
reporter/duration_unit_darwin_test.go
reporter/duration_unit_test.go

I have skipped some tests that check duration measurement on only `macos-latest`. This PR enables to run it on `macos-latest` by increase the test duration unit.

test: allow to run tests on macos-latest

---

reporter/duration_measurer.go
reporter/duration_measurer_test.go
reporter/duration_test.go
reporter/reporter.go
reporter/reporter_test.go
reporter/testing.go

Test duration time didn't include the execution time of sub-tests running in parallel. (this behavior from Go's test command) It is not intuitive, so this PR changes the specification.
```go
package main
import (
"os"
"testing"
"time"
"github.com/zoncoen/scenarigo/reporter"
)
func TestDuration(t *testing.T) {
reporter.Run(func(r reporter.Reporter) {
r.Run("example", func(r reporter.Reporter) {
r.Run("1", func(r reporter.Reporter) {
r.Parallel()
time.Sleep(time.Second)
})
r.Run("2", func(r reporter.Reporter) {
r.Parallel()
time.Sleep(time.Second)
})
r.Run("3", func(r reporter.Reporter) {
r.Parallel()
time.Sleep(time.Second)
})
})
}, reporter.WithWriter(os.Stdout), reporter.WithMaxParallel(3))
}
```
```
--- PASS: example (0.00s)
--- PASS: example/1 (1.00s)
--- PASS: example/2 (1.00s)
--- …
```

feat(reporter): include the execution time of sub-tests

---

reporter/duration_test.go
reporter/log.go
reporter/log_test.go
reporter/report.go
reporter/report_test.go
reporter/reporter.go
reporter/reporter_test.go
reporter/testdata/report.xml
reporter/testing.go
step.go
test/e2e/scenario_test.go
test/e2e/testdata/plugins/simple/main.go
test/e2e/testdata/scenarios/included.yaml
test/e2e/testdata/scenarios/report.yaml

Add a function `GenerateTestReport` that generates a test report `*TestReport`.
The report can be marshaled as JUnit-like format XML.
```go
r, err := scenarigo.NewRunner(
scenarigo.WithScenarios("testdata/example.yaml"),
)
if err != nil {
panic(err)
}
ok := reporter.Run(func(rptr reporter.Reporter) {
r.Run(context.New(rptr))
report, err := reporter.GenerateTestReport(rptr)
if err != nil {
panic(err)
}
jb, err := json.MarshalIndent(report, "", "  ")
if err != nil {
panic(err)
}
fmt.Println(string(jb))
xb, err := xml.MarshalIndent(report, "", "  ")
if err != nil {
panic(err)
}
fmt.Println(string(xb))
})
if !ok {
panic("test failed")
}
```
```json
{
"result": "passed",
"files": [
{
"name": "testdata/example.yaml",
"result": "passed",
"duration": "1.0173ms",
"scenarios": [
{
"name": "/echo", …
```

feat(reporter): enable to generate test report

---

step.go
test/e2e/testdata/scenarios/included.yaml
test/e2e/testdata/scenarios/report.yaml

Scenarigo enables to bind vars defined in the included scenario, but #83 makes it impossible.
This PR fixes it.

fix: enable to bind vars defined in the included scenario

---

context/assert.go
context/assert_test.go
context/testdata/assertion/and.yaml
context/testdata/assertion/contains.yaml
context/testdata/assertion/or.yaml
internal/testutil/parameterized.go
internal/testutil/parameterized_test.go
internal/testutil/reporter.go
internal/testutil/testdata/parameterized-failure.yaml
internal/testutil/testdata/parameterized-invalid.yaml
internal/testutil/testdata/parameterized-success.yaml
template/template.go
template/template_test.go

Left arrow functions require arguments must be a string to decode it as YAML. Because of that, I added a workaround that replacing assert functions with strings temporarily. This PR will fix a bug of the workaround.

fix(assert): fix the assertion operators

---

protocol/grpc/expect.go
protocol/grpc/expect_test.go
protocol/grpc/grpc.go
protocol/grpc/grpc_test.go
protocol/grpc/request.go
protocol/grpc/request_test.go
protocol/http/http.go
protocol/http/http_test.go
test/e2e/e2e_test.go
test/e2e/testdata/scenarios/grpc.yaml
test/e2e/testdata/testcases/backward-compatibility.yaml
test/e2e/testdata/testcases/scenarios/backward-compatibility/body.yaml
test/e2e/testdata/testcases/scenarios/backward-compatibility/expect-body-and-message.yaml
test/e2e/testdata/testcases/scenarios/backward-compatibility/request-body-and-message.yaml
test/e2e/testdata/testcases/scenarios/grpc-enum.yaml
test/e2e/testdata/testcases/stdout/backward-compatibility/body.yaml
test/e2e/testdata/testcases/stdout/backward-compatibility/expect-body-and-message.yaml
test/e2e/testdata/testcases/stdout/backward-compatibility/request-body-and-message.yaml

The payload of gRPC is called "message", not "body".
The `body` field maps to the `message` field for backward compatibility.

fix(grpc): rename body field to message

---

.chglog/CHANGELOG.tpl.md
.github/workflows/test.yml
README.md
protocol/http/request.go
reporter/report_test.go
scenario_test.go
schema/load.go
template/parser/scanner.go
test/e2e/e2e_test.go

ioutil package to be deprecated in Go 1.16.
BREAKING CHANGE: This package requires Go 1.16 or later.

refactor: don't use ioutil package

---

.github/workflows/test.yml
codecov.yml
internal/reflectutil/set.go
internal/reflectutil/set_test.go
template/execute.go
template/execute_test.go
template/lookup.go
template/template.go
template/template_test.go

Left arrow function arguments must be a YAML string. The variables included in the argument are marshaled to YAML string once and concatenated with other strings.
```yaml
{{laf <-}}:
- '{{data}}'
```
```yaml
{{laf <-}}:
- a: 1
b: 2
```
The marshaled YAML string must be concatenated with proper indents to keep its structure.
```yaml
{{laf <-}}:
- a: 1
b: 2
```
fix #124

Add indents to keep the YAML string structure of left arrow function arguments

---

template/execute.go
template/execute_test.go
template/template.go
template/template_test.go

Quote number strings (e.g., "123") to avoid interpreting as not string.

fix(template): marshal variables to YAML in LAF arguments

---

.goreleaser.yml

`plugin` package requires CGO.
Fix #132.

fix: enable CGO on release build

---

.github/workflows/generate-credits.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/test.yml
protocol/grpc/workaround_go1.17.go

Go 1.17 may have a linker bug.
When loading plugins that have `grpc.Dial()` function call, the Go linker raises the error `fatal error: unreachable method called. linker bug?`.
This PR adds a workaround to avoid the bug.
ref. https://github.com/zoncoen/scenarigo/issues/136

add workaround to avoid the bug of Go 1.17

---

mock/protocol/http/handler.go
mock/protocol/http/handler_test.go
mock/protocol/http/testdata/http-expect.yaml
template/execute.go
template/execute_test.go
template/parser/parser_test.go
template/parser/scanner.go
template/parser/scanner_test.go
template/template.go
test/e2e/e2e_test.go
test/e2e/testdata/testcases/left-arrow-function.yaml
test/e2e/testdata/testcases/mocks/left-arrow-function.yaml
test/e2e/testdata/testcases/scenarios/left-arrow-function.yaml
test/e2e/testdata/testcases/stdout/left-arrow-function.txt

It is very annoying for users to write complicated left arrow function calls because they have to write in a single string literal.
```yaml
- title: POST /echo
vars:
message: |-
{{plugins.complex.Join <-}}:
prefix: preout-
text: |-
{{plugins.complex.Join <-}}:
prefix: prein-
text: '{{vars.text}}'
suffix: -sufin
suffix: -sufout
```
This PR enables writing left arrow function call as mapping.
```yaml
- title: POST /echo
vars:
message:
'{{plugins.complex.Join <-}}':
prefix: preout-
text:
'{{plugins.complex.Join <-}}':
prefix: prein-
text: '{{vars.text}}'
suffix: -sufin
suffix: -sufout
```

feat(template): allow writing left arrow function call in map syntax

---

cmd/scenarigo/cmd/run_test.go
cmd/scenarigo/cmd/testdata/scenarigo-plugin-not-found.yaml
runner.go

Don't call log methods of root reporter.

fix: print error if fail to open plugin

---

internal/reflectutil/type.go
protocol/grpc/expect_test.go
protocol/grpc/request.go
protocol/grpc/type.go
template/template.go
template/template_test.go

This PR enables template functions to return errors.
```go
tmpl, _ := template.New(`{{fn()}}`)
_, err := tmpl.Execute(map[string]interface{}{
"fn": func() (string, error) { return "", errors.New("fn() error") },
})
fmt.Println(err)
```
=> `failed to execute: {{fn()}}: fn() error`

feat(template): allow functions to return an error

---

cmd/scenarigo/cmd/plugin/build.go
cmd/scenarigo/cmd/plugin/build_test.go

Downloaded plugin modules should be removed because their go.mod may have been modified.

fix(plugin): remove plugin modules from the cache

---

scripts/cross-build/build-matrix/main.go

Go1.19 has been released.
> Each major Go release is supported until there are two newer major releases.
https://go.dev/doc/devel/release#policy
```sh
$ go run ./build-matrix/main.go
["1.19.1","1.18.6","1.19","1.18.5","1.18.4","1.18.3","1.18.2","1.18.1","1.18"]
```

chore(release): remove go1.17

---

step.go
test/e2e/testdata/testcases/include.yaml
test/e2e/testdata/testcases/mocks/include/failure.yaml
test/e2e/testdata/testcases/mocks/include/success.yaml
test/e2e/testdata/testcases/scenarios/include/included.yaml
test/e2e/testdata/testcases/scenarios/include/scenario.yaml
test/e2e/testdata/testcases/stdout/include/failure.txt
test/e2e/testdata/testcases/stdout/include/success.txt

Stop outputting unnecessary logs to make isolating the root cause easier.
```
--- FAIL: testdata/testcases/scenarios/include/scenario.yaml (0.00s)
--- FAIL: testdata/testcases/scenarios/include/scenario.yaml/included_scenario_fails (0.00s)
--- FAIL: testdata/testcases/scenarios/include/scenario.yaml/included_scenario_fails/include (0.00s)
--- FAIL: testdata/testcases/scenarios/include/scenario.yaml/included_scenario_fails/include/included.yaml (0.00s)
5 |   include: './included.yaml'
6 |   bind:
7 |     vars:
>  8 |       message: '{{vars.message}}'
^
invalid bind: failed to execute: {{vars.message}}: ".vars.message" not found
--- FAIL: testdata/testcases/scenarios/include/scenario.yaml/included_scenario_fails/include/included.yaml/ (0.00s)
[0] send request
request:
method: GET
url: …
```

fix: don't bind vars if included scenario failed

---

go.mod
go.sum
schema/config_test.go

SSIA
[changelog](https://github.com/goccy/go-yaml/compare/v1.9.8...v1.10.0)

chore(deps): bump goccy/go-yaml from v1.9.8 to v1.10.0

---

runner_test.go
schema/load.go
schema/load_test.go

[`(*Decoder).DecodeFromNode`](https://pkg.go.dev/github.com/goccy/go-yaml@v1.11.0#Decoder.DecodeFromNode) seems to have a bug. We must convert the AST Nodes to a string once and then decode it to avoid the issue.
resolve #304

fix(schema): add a workaround to avoid failing to load scenarios

---

Makefile
scripts/cross-build/cross-build/main.go
scripts/cross-build/cross-build/templates/goreleaser.yml.tmpl

`archives.replacements` has been deprecated. https://goreleaser.com/deprecations/#archivesreplacements

chore: fix goreleaser config

---

reporter/duration_test.go
reporter/reporter_non_race_test.go

[The change](https://github.com/golang/go/commit/213495a4a67c318a1fab6e76093e6690c2141c0e#diff-fca95769950854d54b8704162c0b104c189ed1096633227c1cbbf0c49739ccde) may cause a data race.
https://github.com/zoncoen/scenarigo/actions/runs/6105004393/job/16567842172?pr=331

chore: run panic(nil) test case w/o race detector

---

README.md
runner.go
runner_test.go
schema/config.go
test/e2e/e2e_test.go
test/e2e/testdata/testcases/scenarios/include/included.yaml
test/e2e/testdata/testcases/stdout/include/failure.txt

Add `vars` field to the config file. The defined values can be used in all scenarios.
```yaml scenarigo.yaml
schemaVersion: config/v1
vars:
endpoint: http://api.example.com
```
```
steps:
- title: GET /foo
protocol: http
request:
method: GET
url: '{{vars.endpoint}}/foo'
expect:
code: OK
```

feat(config): add global variables

---

protocol/grpc/expect_test.go
protocol/grpc/request.go
protocol/grpc/request_test.go

gRPC allows to store binary data in metadata with the key having `-bin` suffix.
ref. https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md#storing-binary-data-in-metadata

feat(grpc): dump invalid utf8 strings as hex

---

assert/assertion.go
assert/assertion_test.go
context/assert_test.go
context/template.go
context/testdata/assertion/and.yaml
context/testdata/assertion/contains.yaml
context/testdata/assertion/or.yaml
errors/error.go
errors/error_test.go
template/execute.go
template/execute_test.go
template/lazy.go
template/lazy_test.go
template/lookup.go
template/once.go
template/once_go_120.go
template/template.go
template/template_test.go
test/e2e/testdata/scenarios/assert.yaml

This change fixes the issue caused by complex assertions like the following.
```yaml
expect:
body:
'{{assert.and <-}}':
- '{{assert.contains <-}}':
name: Alice
age: '{{int($) >= 20}}'
- '{{assert.contains <-}}':
name: '{{"Bob"}}'
```

fix(assert): fix errors when using assert.(and|or)

---

template/parser/parser.go
template/parser/parser_test.go
template/template.go
template/template_test.go
template/token/token.go

SSIA
e.g., `id-{{1}}` -> `id-1`

fix(template): convert into string in implicit concatenation

---

template/execute.go
template/execute_test.go
template/lazy.go
template/lazy_test.go
test/e2e/testdata/testcases/mocks/retry/laf.yaml
test/e2e/testdata/testcases/retry.yaml
test/e2e/testdata/testcases/scenarios/retry/laf.yaml
test/e2e/testdata/testcases/stdout/retry/laf.txt

`replaceFuncs` breaks the original value.

fix(assert): fix retry failure if using left arrow functions for assertion

---

template/parser/parser_test.go
template/parser/scanner.go

The whitespace skip process did not include new-line-char, so this has been fixed.

Fix parsing of template contains new line char

---

cmd/scenarigo/cmd/plugin/build.go
cmd/scenarigo/cmd/plugin/build_test.go
reporter/duration_unit_darwin_test.go
reporter/duration_unit_test.go

When building a plugin, imports of the old module `github.com/zoncoen/scenarigo` will be automatically replaced with the new module `github.com/scenarigo/scenarigo`. To disable this migration behavior, use the `--skip-migration` option.

feat(plugin): migrate automatically from zoncoen/scenarigo to scenarigo/scenarigo
